name: Configure Copilot Environment

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: ".NET SDK version to use"
        default: "8.0.x"
        required: false
        type: string

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version || '8.0.x' }}
      
      - name: Configure NuGet feed
        run: |
          if ! dotnet nuget list source | grep -q "nuget.org"; then
            dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
          else
            echo "NuGet.org source already exists, skipping..."
          fi
      
      - name: Prepare common dotnet packages
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
      
      - name: Configure Firewall
        run: |
          echo "Allow access to nuget.org domains"
          echo "api.nuget.org" >> $GITHUB_WORKSPACE/.github/copilot-firewall-allowlist
          echo "dc.services.visualstudio.com" >> $GITHUB_WORKSPACE/.github/copilot-firewall-allowlist
          echo "*.nuget.org" >> $GITHUB_WORKSPACE/.github/copilot-firewall-allowlist
          echo "crl3.digicert.com" >> $GITHUB_WORKSPACE/.github/copilot-firewall-allowlist
          echo "crl4.digicert.com" >> $GITHUB_WORKSPACE/.github/copilot-firewall-allowlist
          echo "ocsp.digicert.com" >> $GITHUB_WORKSPACE/.github/copilot-firewall-allowlist
          echo "s.symcb.com" >> $GITHUB_WORKSPACE/.github/copilot-firewall-allowlist
          echo "s.symcd.com" >> $GITHUB_WORKSPACE/.github/copilot-firewall-allowlist
          echo "ts-crl.ws.symantec.com" >> $GITHUB_WORKSPACE/.github/copilot-firewall-allowlist
          echo "ts-ocsp.ws.symantec.com" >> $GITHUB_WORKSPACE/.github/copilot-firewall-allowlist
          echo "cdn.fwupd.org" >> $GITHUB_WORKSPACE/.github/copilot-firewall-allowlist
